# Generated by Django 3.0.6 on 2020-06-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200530_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subcategory',
            field=models.ManyToManyField(to='projects.Subcategory'),
        ),
    ]
