# Generated by Django 3.0.6 on 2020-06-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200530_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='subcategory',
            new_name='subcategories',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='subcategories',
            field=models.ManyToManyField(to='projects.Subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='projects.Subcategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='projects.Subcategory'),
        ),
    ]
