# Generated by Django 3.0.6 on 2020-06-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200601_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subcategory',
            field=models.ManyToManyField(to='projects.Subcategory'),
        ),
    ]
