# Generated by Django 3.0.7 on 2020-06-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_app_changes'),
        ('projects', '0003_auto_20200608_2134'),
    ]

    operations = [
    ]
