version: "3.8"

services:
  pjbook_db:
    image: postgres:9.6
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    container_name: pjbook_db
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pjbook_web:
    build: .
    container_name: pjbook_web
    command: bash -c "python manage.py migrate --noinput &&
                      python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/pjbook/
    ports:
      - "8001:8001"
    depends_on:
      - pjbook_db

volumes:
  postgres_data:
  pjbook: